(extend av-rule-3)
(extend av-rule-17)
(extend av-rule-19)
(extend av-rule-20)
(extend av-rule-21)
(extend av-rule-22)
(extend av-rule-23)
(extend av-rule-24)
(extend av-rule-25)
(extend av-rule-189)
(extend jpl-rule-4)
(option log-dir log)
